# Generated by Django 5.2.6 on 2025-10-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='user',
        ),
    ]
