# Generated by Django 5.2.6 on 2025-09-30 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_order', models.JSONField(verbose_name='Ordem das questões')),
                ('current_index', models.SmallIntegerField(default=0, verbose_name='Índice atual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionset', verbose_name='Conjunto de Questões')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de prática',
                'verbose_name_plural': 'Sessões de práticas',
            },
        ),
        migrations.CreateModel(
            name='PracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.choice', verbose_name='Alternativa')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Questão')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.practicesession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Resposta da prática',
                'verbose_name_plural': 'Respostas das práticas',
            },
        ),
    ]
