# Generated by Django 5.2.6 on 2025-10-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='pinned_at',
            field=models.DateTimeField(null=True, verbose_name='Fixado em'),
        ),
    ]
